import type { Asset, IntegrationSource, PanelScheduleData } from "@/types/domain";

// Wing 2 is the V1 deployment boundary. Primary areas are active; D/E 600-700
// are shown but excluded from scope until the platform expands.
export const WING2_AREAS = [
  { id: "A500", active: true },
  { id: "A600", active: true },
  { id: "A700", active: true },
  { id: "B500", active: true },
  { id: "B600", active: true },
  { id: "B700", active: true },
  { id: "C500", active: true },
  { id: "C600", active: true },
  { id: "C700", active: true },
  { id: "D600", active: false },
  { id: "D700", active: false },
  { id: "E600", active: false },
  { id: "E700", active: false },
] as const;

export const INTEGRATION_SOURCES: IntegrationSource[] = [
  { id: "sharepoint-panel-schedules", name: "SharePoint Panel Schedules", currentIngestMode: "local_xlsx", futureService: "Microsoft Graph", isActive: true },
  { id: "procore-rfis", name: "Procore RFI Log", currentIngestMode: "csv_export", futureService: "Procore API", isActive: true },
  { id: "airtable-commissioning", name: "Airtable Commissioning Tracker", currentIngestMode: "csv_export", futureService: "Airtable API", isActive: true },
  { id: "facilitygrid", name: "FacilityGrid", currentIngestMode: "csv_xlsx_export", futureService: "API or Tampermonkey bridge", isActive: true },
  { id: "groupme", name: "GroupMe", currentIngestMode: "json_export", futureService: "GroupMe API", isActive: true },
  { id: "excel-trackers", name: "Excel Trackers", currentIngestMode: "local_xlsx", futureService: "Scheduled ingest", isActive: true },
  { id: "bluebeam", name: "Bluebeam Markups", currentIngestMode: "manual_export", futureService: "Bluebeam Studio API", isActive: false },
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: "fsd-13",
    name: "FSD-13",
    area: "B600",
    room: "Cell WH B-6",
    panel: "KSPA1W2-3B1-2A3",
    circuit: "08",
    trade: "Shambaugh & Son, LP",
    status: "blocked",
    inspectionStatus: "TY scheduled — awaiting panel verification",
    facilityGridStatus: "Checklist 3/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-05-02" },
      { label: "Documentation", status: "done", date: "2026-05-14" },
      { label: "TY Inspection", status: "active", date: "2026-07-09" },
      { label: "City Inspection", status: "upcoming" },
      { label: "Energized", status: "upcoming" },
      { label: "Startup", status: "upcoming" },
      { label: "Commissioned", status: "upcoming" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [
      { id: "d1", name: "KSPA1W2-3B1-2A3-FN4 Panel Schedule.xlsx", kind: "schedule", source: "SharePoint", updatedOn: "2026-06-30" },
      { id: "d2", name: "FSD-13 Submittal.pdf", kind: "submittal", source: "Procore", updatedOn: "2026-04-11" },
      { id: "d3", name: "FSD-13 TY Checklist", kind: "checklist", source: "FacilityGrid", updatedOn: "2026-07-01" },
    ],
    photos: [
      { id: "p1", caption: "Damper install — field verification", takenOn: "2026-05-02" },
      { id: "p2", caption: "Controls wiring in progress", takenOn: "2026-06-18" },
    ],
    constraints: [
      { id: "c1", label: "Controls wiring incomplete on CKT08", status: "open", severity: "high", raisedOn: "2026-06-20", note: "Awaiting Shambaugh crew return to close out low-voltage terminations." },
    ],
    comments: [
      { id: "cm1", author: "J. Alvarez", body: "Panel schedule verified against SharePoint, matches field.", postedOn: "2026-06-29", source: "commissionos" },
      { id: "cm2", author: "Wing 2 Trades", body: "FSD-13 energization pushed to next week pending controls fix.", postedOn: "2026-06-28", source: "groupme" },
    ],
    history: [
      { id: "h1", label: "Constraint raised", detail: "Controls wiring incomplete on CKT08", occurredOn: "2026-06-20" },
      { id: "h2", label: "TY inspection scheduled", detail: "Set for 2026-07-09", occurredOn: "2026-06-25" },
    ],
    relatedAssets: [
      { id: "pnl-b600-04", name: "PNL-B600-04", relationship: "Feeds from panel", status: "ready" },
      { id: "bdg-22", name: "BR-22", relationship: "Same panel, CKT12", status: "waiting" },
    ],
  },
  {
    id: "pnl-b600-04",
    name: "PNL-B600-04",
    area: "B600",
    room: "Electrical Room B-6",
    panel: "KSPA1W2-3B1-2A3",
    circuit: "Main",
    trade: "Shambaugh & Son, LP",
    status: "ready",
    inspectionStatus: "TY complete — cleared for city inspection",
    facilityGridStatus: "Checklist 5/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-04-18" },
      { label: "Documentation", status: "done", date: "2026-04-30" },
      { label: "TY Inspection", status: "done", date: "2026-06-02" },
      { label: "City Inspection", status: "active", date: "2026-07-14" },
      { label: "Energized", status: "upcoming" },
      { label: "Startup", status: "upcoming" },
      { label: "Commissioned", status: "upcoming" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [
      { id: "d1", name: "KSPA1W2-3B1-2A3 Panel Schedule.xlsx", kind: "schedule", source: "SharePoint", updatedOn: "2026-06-30" },
    ],
    photos: [{ id: "p1", caption: "Panel labeled and torqued", takenOn: "2026-05-20" }],
    constraints: [],
    comments: [
      { id: "cm1", author: "M. Reyes", body: "City inspection confirmed for 07/14, ready.", postedOn: "2026-07-02", source: "commissionos" },
    ],
    history: [
      { id: "h1", label: "TY inspection passed", detail: "No punch items", occurredOn: "2026-06-02" },
    ],
    relatedAssets: [
      { id: "fsd-13", name: "FSD-13", relationship: "Downstream circuit", status: "blocked" },
    ],
  },
  {
    id: "bdg-22",
    name: "BR-22",
    area: "B600",
    room: "Cell WH B-6",
    panel: "KSPA1W2-3B1-2A3",
    circuit: "12",
    trade: "Kirkham Security Systems",
    status: "waiting",
    inspectionStatus: "Awaiting energization on CKT12 before functional test",
    facilityGridStatus: "Checklist 2/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-06-01" },
      { label: "Documentation", status: "done", date: "2026-06-10" },
      { label: "TY Inspection", status: "upcoming" },
      { label: "City Inspection", status: "upcoming" },
      { label: "Energized", status: "upcoming" },
      { label: "Startup", status: "upcoming" },
      { label: "Commissioned", status: "upcoming" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [
      { id: "d1", name: "BR-22 Cut Sheet.pdf", kind: "submittal", source: "Procore", updatedOn: "2026-06-05" },
    ],
    photos: [{ id: "p1", caption: "Reader mounted, awaiting power", takenOn: "2026-06-01" }],
    constraints: [],
    comments: [
      { id: "cm1", author: "Kirkham Security", body: "Ready to test as soon as CKT12 is live.", postedOn: "2026-06-25", source: "groupme" },
    ],
    history: [{ id: "h1", label: "Installed", detail: "Reader and controller mounted", occurredOn: "2026-06-01" }],
    relatedAssets: [{ id: "fsd-13", name: "FSD-13", relationship: "Same panel, Cell WH B-6", status: "blocked" }],
  },
  {
    id: "ohd-07",
    name: "OHD-07",
    area: "A500",
    room: "Dock Door A-5",
    panel: "KSPA1W2-3A1-2A1",
    circuit: "04",
    trade: "Same Day Overhead Doors",
    status: "commissioned",
    inspectionStatus: "TY and city inspection passed",
    facilityGridStatus: "Checklist 5/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-04-02" },
      { label: "Documentation", status: "done", date: "2026-04-10" },
      { label: "TY Inspection", status: "done", date: "2026-05-01" },
      { label: "City Inspection", status: "done", date: "2026-05-20" },
      { label: "Energized", status: "done", date: "2026-05-22" },
      { label: "Startup", status: "done", date: "2026-06-01" },
      { label: "Commissioned", status: "active", date: "2026-06-10" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [{ id: "d1", name: "OHD-07 Startup Report.pdf", kind: "submittal", source: "Procore", updatedOn: "2026-06-02" }],
    photos: [{ id: "p1", caption: "Operator cycle test — pass", takenOn: "2026-06-01" }],
    constraints: [],
    comments: [{ id: "cm1", author: "Same Day Doors", body: "Cycle tested 25x, no faults.", postedOn: "2026-06-01", source: "commissionos" }],
    history: [{ id: "h1", label: "Commissioned", detail: "Startup report signed off", occurredOn: "2026-06-10" }],
    relatedAssets: [{ id: "pnl-a500-01", name: "PNL-A500-01", relationship: "Feeds from panel", status: "ready" }],
  },
  {
    id: "pnl-a500-01",
    name: "PNL-A500-01",
    area: "A500",
    room: "Electrical Room A-5",
    panel: "KSPA1W2-3A1-2A1",
    circuit: "Main",
    trade: "Same Day Overhead Doors",
    status: "ready",
    inspectionStatus: "TY complete — cleared for city inspection",
    facilityGridStatus: "Checklist 4/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-03-20" },
      { label: "Documentation", status: "done", date: "2026-03-28" },
      { label: "TY Inspection", status: "done", date: "2026-05-05" },
      { label: "City Inspection", status: "active", date: "2026-07-11" },
      { label: "Energized", status: "upcoming" },
      { label: "Startup", status: "upcoming" },
      { label: "Commissioned", status: "upcoming" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [{ id: "d1", name: "KSPA1W2-3A1-2A1 Panel Schedule.xlsx", kind: "schedule", source: "SharePoint", updatedOn: "2026-06-28" }],
    photos: [],
    constraints: [],
    comments: [],
    history: [{ id: "h1", label: "TY inspection passed", detail: "No punch items", occurredOn: "2026-05-05" }],
    relatedAssets: [{ id: "ohd-07", name: "OHD-07", relationship: "Downstream circuit", status: "commissioned" }],
  },
  {
    id: "xfmr-02",
    name: "XFMR-02",
    area: "A700",
    room: "Electrical Room A-7",
    panel: "Utility Feed",
    circuit: "Main",
    trade: "Shambaugh & Son, LP",
    status: "complete",
    inspectionStatus: "Turned over to owner",
    facilityGridStatus: "Checklist 5/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-02-10" },
      { label: "Documentation", status: "done", date: "2026-02-20" },
      { label: "TY Inspection", status: "done", date: "2026-03-01" },
      { label: "City Inspection", status: "done", date: "2026-03-15" },
      { label: "Energized", status: "done", date: "2026-03-20" },
      { label: "Startup", status: "done", date: "2026-04-01" },
      { label: "Commissioned", status: "done", date: "2026-04-15" },
      { label: "AHJ", status: "done", date: "2026-04-25" },
      { label: "Turnover", status: "done", date: "2026-05-01" },
    ],
    documents: [{ id: "d1", name: "XFMR-02 Turnover Package.pdf", kind: "submittal", source: "Procore", updatedOn: "2026-05-01" }],
    photos: [{ id: "p1", caption: "Final infrared scan — pass", takenOn: "2026-04-20" }],
    constraints: [],
    comments: [{ id: "cm1", author: "M. Reyes", body: "Turned over, O&M manuals delivered.", postedOn: "2026-05-01", source: "commissionos" }],
    history: [{ id: "h1", label: "Turned over", detail: "Owner accepted, O&M delivered", occurredOn: "2026-05-01" }],
    relatedAssets: [{ id: "pnl-a500-01", name: "PNL-A500-01", relationship: "Feeds panel", status: "ready" }],
  },
  {
    id: "cam-14",
    name: "CAM-14",
    area: "C600",
    room: "Corridor C-6",
    panel: "KSPA1W2-3C1-2A2",
    circuit: "03",
    trade: "Kirkham Security Systems",
    status: "commissioned",
    inspectionStatus: "Functional test passed",
    facilityGridStatus: "Checklist 5/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-05-10" },
      { label: "Documentation", status: "done", date: "2026-05-18" },
      { label: "TY Inspection", status: "done", date: "2026-06-01" },
      { label: "City Inspection", status: "done", date: "2026-06-12" },
      { label: "Energized", status: "done", date: "2026-06-13" },
      { label: "Startup", status: "done", date: "2026-06-20" },
      { label: "Commissioned", status: "active", date: "2026-06-25" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [{ id: "d1", name: "CAM-14 Test Report.pdf", kind: "checklist", source: "FacilityGrid", updatedOn: "2026-06-25" }],
    photos: [{ id: "p1", caption: "Field of view verified", takenOn: "2026-06-20" }],
    constraints: [],
    comments: [],
    history: [{ id: "h1", label: "Commissioned", detail: "Recording confirmed to NVR", occurredOn: "2026-06-25" }],
    relatedAssets: [{ id: "fa-118", name: "FA-118", relationship: "Same panel", status: "blocked" }],
  },
  {
    id: "fa-118",
    name: "FA-118",
    area: "C700",
    room: "Cell WH C-7",
    panel: "KSPA1W2-3C1-2A2",
    circuit: "06",
    trade: "Shambaugh & Son, LP",
    status: "blocked",
    inspectionStatus: "TY failed — device address conflict",
    facilityGridStatus: "Checklist 2/5 complete",
    timeline: [
      { label: "Installed", status: "done", date: "2026-06-05" },
      { label: "Documentation", status: "done", date: "2026-06-12" },
      { label: "TY Inspection", status: "blocked", date: "2026-06-28" },
      { label: "City Inspection", status: "upcoming" },
      { label: "Energized", status: "upcoming" },
      { label: "Startup", status: "upcoming" },
      { label: "Commissioned", status: "upcoming" },
      { label: "AHJ", status: "upcoming" },
      { label: "Turnover", status: "upcoming" },
    ],
    documents: [{ id: "d1", name: "FA-118 TY Punch List.pdf", kind: "checklist", source: "FacilityGrid", updatedOn: "2026-06-28" }],
    photos: [{ id: "p1", caption: "Device address label", takenOn: "2026-06-28" }],
    constraints: [
      { id: "c1", label: "Device address conflict with FA-119", status: "open", severity: "medium", raisedOn: "2026-06-28", note: "Re-address FA-118 on the loop and retest before next TY window." },
    ],
    comments: [{ id: "cm1", author: "J. Alvarez", body: "Flagged during TY, re-inspection requested for next week.", postedOn: "2026-06-28", source: "commissionos" }],
    history: [{ id: "h1", label: "TY inspection failed", detail: "Device address conflict with FA-119", occurredOn: "2026-06-28" }],
    relatedAssets: [{ id: "cam-14", name: "CAM-14", relationship: "Same panel", status: "commissioned" }],
  },
];

export function getAssetById(id: string): Asset | undefined {
  return MOCK_ASSETS.find((asset) => asset.id === id);
}

export const MOCK_PANEL_SCHEDULES: PanelScheduleData[] = [
  {
    // Demo fixture mirroring the PJKS Energized Circuits reference screen:
    // two-bank breaker layout, a 3-pole 125A sub-feed on ckts 2/4/6, and a mix
    // of Energized / Future / BLANK positions.
    panelId: "KSPA1W2-8J1-1A3-GE2-2A",
    panelName: "8J1-1A3-GE2-2A",
    permitNumber: "2248",
    scheduleName: "GE2-56 (2)",
    circuits: [
      { circuit: "1", description: "KSPA1W2-FSD-01", load: "20A", status: "future" },
      { circuit: "2", description: "KSPA1W2-8J1-1A3-GE2-2B", load: "125A", status: "energized" },
      { circuit: "3", description: "KSPA1W2-FSD-02", load: "20A", status: "energized" },
      { circuit: "4", description: "KSPA1W2-8J1-1A3-GE2-2B", load: "125A", status: "energized" },
      { circuit: "5", description: "KSPA1W2-FSD-03", load: "20A", status: "future" },
      { circuit: "6", description: "KSPA1W2-8J1-1A3-GE2-2B", load: "125A", status: "energized" },
      { circuit: "7", description: "KSPA1W2-FSD-36/37", load: "20A", status: "future" },
      { circuit: "8", description: "BLANK", load: "", status: "blank" },
      { circuit: "9", description: "KSPA1W2-FSD-39", load: "20A", status: "energized" },
      { circuit: "10", description: "BLANK", load: "", status: "blank" },
      { circuit: "11", description: "BLANK", load: "", status: "blank" },
      { circuit: "12", description: "BLANK", load: "", status: "blank" },
      { circuit: "13", description: "BLANK", load: "", status: "blank" },
      { circuit: "14", description: "BLANK", load: "", status: "blank" },
      { circuit: "15", description: "BLANK", load: "", status: "blank" },
      { circuit: "16", description: "BLANK", load: "", status: "blank" },
      { circuit: "17", description: "BLANK", load: "", status: "blank" },
    ],
  },
  {
    panelId: "KSPA1W2-3B1-2A3",
    panelName: "PNL-B600-04",
    circuits: [
      { circuit: "01", description: "Panel main feed", load: "225A", status: "energized" },
      { circuit: "02", description: "Lighting — Cell WH B-6", load: "20A", status: "energized" },
      { circuit: "05", description: "Overhead door OHD-04 operator", load: "30A", status: "energized" },
      { circuit: "08", description: "FSD-13 controls", load: "20A", status: "blocked" },
      { circuit: "09", description: "Spare", load: "—", status: "spare" },
      { circuit: "12", description: "Badge reader BR-22", load: "5A", status: "de-energized" },
    ],
  },
  {
    panelId: "KSPA1W2-3A1-2A1",
    panelName: "PNL-A500-01",
    circuits: [
      { circuit: "01", description: "Panel main feed", load: "400A", status: "energized" },
      { circuit: "04", description: "Overhead door OHD-07 operator", load: "30A", status: "energized" },
      { circuit: "06", description: "Lighting — Dock Door A-5", load: "20A", status: "energized" },
      { circuit: "10", description: "Spare", load: "—", status: "spare" },
    ],
  },
  {
    panelId: "KSPA1W2-3C1-2A2",
    panelName: "PNL-C600-02",
    circuits: [
      { circuit: "01", description: "Panel main feed", load: "225A", status: "energized" },
      { circuit: "03", description: "Camera CAM-14", load: "5A", status: "energized" },
      { circuit: "06", description: "Fire alarm loop — FA-118/FA-119", load: "10A", status: "blocked" },
      { circuit: "07", description: "Spare", load: "—", status: "spare" },
    ],
  },
];

export function getPanelSchedule(panelId: string): PanelScheduleData | undefined {
  return MOCK_PANEL_SCHEDULES.find((schedule) => schedule.panelId === panelId);
}

export function getAssetsByPanel(panelId: string): Asset[] {
  return MOCK_ASSETS.filter((asset) => asset.panel === panelId);
}
